apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/components-aipipelines
  - ../../components/components-feast
  - ../../components/components-kserve
  - ../../components/components-kserve-maas
  - ../../components/components-mlflow
  - ../../components/components-mlflow-basic-instance
  - ../../components/components-modelregistry
  - ../../components/components-observability
  - ../../components/components-ogx
  - ../../components/components-ray
  - ../../components/components-trainingoperator
  - ../../components/components-trustyai
  - ../../components/components-workbenches
  - ../../components/hardware-profiles-nvidia-gpu
  - ../../components/idle-notebook-culling
  - ../../components/inference-gateway
  - ../../components/maas-postgres-cnpg
  - ../../components/rhoai-auth
