apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-cluster-config-app-of-apps.yaml
    target:
      kind: Application
      name: cluster-config-app-of-apps
  - path: patch-operators-list.yaml
    target:
      kind: ApplicationSet
      name: cluster-operators
  - path: patch-configs-list.yaml
    target:
      kind: ApplicationSet
      name: cluster-configs
  # Removing the tenants, since these will be moving to a separate GitOps repo at
  # https://github.com/redhat-ai-services/ai-accelerator-examples
  # - path: patch-tenants-applicationset.yaml
  #   target:
  #     kind: ApplicationSet
  #     name: tenants
