apiVersion: batch/v1
kind: Job
metadata:
  name: upload-model-to-s3
spec:
  selector: {}
  template:
    spec:
      containers:
        - name: upload-model-to-s3
          image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:2024.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: aws-connection-example
          env:
            - name: SUBDIR_MODEL_PATH
              value: ""
            - name: PREFIX_PATH
              value: models  # since repo is in the models dir, copy whatever is in the models folder
            - name: MODEL_PATH
              value: "$(PREFIX_PATH)/$(SUBDIR_MODEL_PATH)"
          command:
            - /bin/bash
          args:
            - -ec
            - |-
              python3 /scripts/upload-model-to-s3.py
          volumeMounts:
            - name: src
              mountPath: /opt/app-root/src
            - name: scripts
              mountPath: /scripts
      initContainers:
        - name: git-cloner
          # image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          image: alpine/git:2.43.0
          env:
            - name: MODEL_NAME
              value: granite-3b-code-base
            - name: REPO_URL
              value: https://huggingface.co/ibm-granite/granite-3b-code-base.git
            # - name: GIT_CLONE_PROTECTION_ACTIVE
            #   value: "false"
          command:
            - /bin/sh
            - -c
            - -e
            - git clone --single-branch -- $(REPO_URL) /opt/app-root/src/models/$(MODEL_NAME)
            - ls -laFh /opt/app-root/src/models/$(MODEL_NAME)
          volumeMounts:
            - mountPath: /opt/app-root/src/
              name: src
      volumes:
        - name: src
          emptyDir: {}
        - name: scripts
          configMap:
            name: upload-model-to-s3
      restartPolicy: Never
