apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ./copy-trusted-ca

resources:
  - ca-clusterissuer.yaml
  - cluster-proxy.yaml
  - selfsigned-clusterissuer.yaml
  - selfsigned-certificate.yaml

