apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-example-trustyai-demo

labels:
  - includeSelectors: true
    pairs:
      app: minio
  - includeSelectors: false
    pairs:
      app.kubernetes.io/component: minio

resources:
  - deployment.yaml
  - routes.yaml
  - secret.yaml
  - service.yaml
  - trustyai_service.yaml
  - service_account.yaml
  - role_binding.yaml
  - data-connection.yaml
