apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/kueue-operator.openshift-kueue-operator: ""
  name: kueue-operator
  namespace: openshift-kueue-operator
spec:
  channel: stable-v1.0
  installPlanApproval: Automatic
  name: kueue-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: kueue-operator.v1.0.1
