apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-cluster-observability-operator

components:
  - ../../components/v1.4.0 # pin to v1.4.0 due to issues with 1.5.0  

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: cluster-observability-operator
    path: patch-channel.yaml
