---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kuadrant-system

# components:
#   - ../../components/v1.3.4 # pin to v1.3.4 due to issues with 1.4.0

resources:
  - ../../base

components:
  - ../../components/enable-console-plugin

patches:
  - path: patch-channel.yaml
    target:
      group: operators.coreos.com
      kind: Subscription
