apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - ../../../instance-3.x/overlays/beta-nvidia-gpu
  - ../../../operator/overlays/beta
