apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  # - ../../../../../../scripts/library
  - job.yaml
  - rbac.yaml
  - patch-device-plugin-config.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: job-aws-gpu-machineset
    namespace: nvidia-gpu-operator
    files:
      - job.sh
      - machineset-patch.yaml
patches:
  - path: patch-gpu-cluster-policy.yaml
    target:
      kind: ClusterPolicy
  - path: job.yaml
    target:
      kind: Job
