apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    cluster-api/accelerator: "nvidia-gpu"
spec:
  template:
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/gpu: ""
          cluster-api/accelerator: "nvidia-gpu"
      taints:
        - key: nvidia.com/gpu
          effect: NoSchedule
