apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - files:
      - delete-rhoai-resources.sh
    name: rhoai-cleanup-script
    namespace: openshift-gitops

patches:
  - patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/hook: PreDelete
          argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
          argocd.argoproj.io/sync-wave: "-1"
    target:
      kind: ConfigMap
      name: rhoai-cleanup-script

resources:
  - delete-rhoai-resources.yaml
