kind: Namespace
apiVersion: v1
metadata:
  name: redhat-ai-gateway-infra
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    maas.opendatahub.io/gateway-access: 'true'
