apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default
spec:
  components:
    aigateway:
      managementState: Managed
      modelsAsAService:
        managementState: Managed
