---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-copy-trusted-ca
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-copy-trusted-ca
  namespace: cert-manager
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - cert-manager-ca
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-copy-trusted-ca
  namespace: cert-manager
subjects:
  - kind: ServiceAccount
    name: job-copy-trusted-ca
    namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-copy-trusted-ca
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-copy-trusted-ca
  namespace: openshift-config
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-copy-trusted-ca
  namespace: openshift-config
subjects:
  - kind: ServiceAccount
    name: job-copy-trusted-ca
    namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-copy-trusted-ca
