apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../../base
  - ../../../components/argocd/apps/overlays/parasol-insurance-dev

patches:
  # set the repo and branch for applications
  - path: patch-application-repo-revision.yaml
    target:
      group: argoproj.io
      kind: Application

replacements:
  - source:
      kind: Application
      fieldPath: spec.source.repoURL
    targets:
      - select:
          kind: ApplicationSet
        fieldPaths:
          - spec.template.spec.source.repoURL
      - select:
          kind: ApplicationSet
          name: tenants
        fieldPaths:
          - spec.generators.*.git.repoURL
  - source:
      kind: Application
      fieldPath: spec.source.targetRevision
    targets:
      - select:
          kind: ApplicationSet
        fieldPaths:
          - spec.template.spec.source.targetRevision
      - select:
          kind: ApplicationSet
          name: tenants
        fieldPaths:
          - spec.generators.*.git.revision
