apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/mcp-gateway.openshift-operators: ''
  name: mcp-gateway
spec:
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  name: mcp-gateway
  source: redhat-operators
  sourceNamespace: openshift-marketplace
