apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rhcl-operator.openshift-operators: ''
  name: rhcl-operator
spec:
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  name: rhcl-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
