apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llama-stack-k8s-operator-controller-manager

resources:
- cluster-rbac.yaml
- configmap.yaml
- crd.yaml
- deployment.yaml
- namespace.yaml
- rbac.yaml
- service.yaml
- serviceaccount.yaml
