apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redhat-ods-applications

resources:
  - ../../base
# TODO: Check with Trevor whether its okay to replace components-serving
# with components-kserve and components-modelmesh.
# TODO: Check with Trevor whether its okay to remove   - ../../components/runtime-template-triton
components:
  - ../../components/components-kserve
  - ../../components/components-modelmesh
  - ../../components/components-training
  - ../../components/components-trustyai
  - ../../components/default-notebook-pvc-size
  - ../../components/idle-notebook-culling
  - ../../components/notebook-pod-sizes
  - ../../components/make-kubeadmin-cluster-admin
  - ../../components/model-server-pod-sizes
  - ../../components/rhoai-dashboard-access
  - ../../components/auth-with-authorino
  - ../../components/rhoai-auth
