apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-scc-anyuid
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - anyuid
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llama-stack-playground-use-scc-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-scc-anyuid
subjects:
- kind: ServiceAccount
  name: llama-stack-playground