apiVersion: v1
kind: ServiceAccount
metadata:
  name: llama-stack-playground
  labels:
    helm.sh/chart: llama-stack-playground-1.0.0
    app.kubernetes.io/name: llama-stack-playground
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"llama-stack-playground"}}'
