kind: Service
apiVersion: v1
metadata:
  name: authorino-authorino-authorization
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  listener:
    tls:
      enabled: true
      certSecretRef:
        name: authorino-server-cert
