kind: Service
apiVersion: v1
metadata:
  name: authorino-authorino-authorization
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
    service.beta.openshift.io/serving-cert-secret-name: authorino-server-cert
spec:
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
