apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/cluster-config-app-of-apps.yaml
  - ../../base/cluster-configs-applicationset.yaml
  - ../../base/cluster-operators-applicationset.yaml

patches:
  - path: patch-cluster-config-app-of-apps.yaml
    target:
      kind: Application
      name: cluster-config-app-of-apps
  - path: patch-operators-list.yaml
    target:
      kind: ApplicationSet
      name: cluster-operators
  - path: patch-configs-list.yaml
    target:
      kind: ApplicationSet
      name: cluster-configs
  - path: patch-tenants-applicationset.yaml
    target:
      kind: ApplicationSet
      name: tenants
