---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-patch-route-host
  namespace: openshift-ingress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-patch-route-host
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - console-public
    verbs:
      - get
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes/custom-host
    verbs:
      - create
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-patch-route-host
subjects:
  - kind: ServiceAccount
    name: job-patch-route-host
    namespace: openshift-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-patch-route-host
