---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./installplan-approver

patches:
  - path: subscription-patch.yaml
    target:
      kind: Subscription
      name: rhcl-operator
