apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: mcp-gateway

resources:
  - patch-route-host-job.yaml
  - rbac.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: job-patch-route-host
    namespace: mcp-gateway
    files:
      - patch-route-host.sh
