apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-configs
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: cluster-autoscaling
          path: components/cluster-configs/autoscaling/overlays/default
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: htpasswd
            path: components/cluster-configs/htpasswd/overlays/maas
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: selfsigned-internal-ca
          path: components/cluster-configs/self-signed-internal-ca/overlays/default
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: user-workload-monitoring
          path: components/cluster-configs/user-workload-monitoring/overlays/default
