apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-gateway

resources:
  - gateway.yaml
  - gatewayclass.yaml
  - mcpgatewayextension.yaml
  - referencegrant.yaml
  - route.yaml

components:
  - ./route-hostname-job
