apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parasol-insurance

resources:
  - standard-workbench-pvc.yaml
  - minio-data-connection.yaml
  - standard-workbench-notebook.yaml
