apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config-app-of-apps
  namespace: openshift-gitops
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: patch-me-see-overlays
    repoURL: https://github.com/redhat-ai-services/ai-accelerator.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
