apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default
spec:
  components:
    trustyai:
      managementState: Managed
      eval:
        lmeval:
          permitCodeExecution: deny
          permitOnline: deny
