apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: demo-loan-nn-onnx-beta
    # security.opendatahub.io/enable-auth: "true"
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  labels:
    opendatahub.io/dashboard: "true"
  name: demo-loan-nn-onnx-beta
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: onnx
        version: '1'
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
        requests:
          cpu: '2'
          memory: 8Gi
      runtime: ovms-1.x
      storage:
        key: aws-connection-trustyai-demo
        path: ovms/loan_model_beta
