apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/accelerator-name: ""
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: OpenVINO Model Server
    opendatahub.io/template-name: kserve-ovms
    openshift.io/display-name: ovms-1.x
    prometheus.io/path: /metrics
    prometheus.io/port: "8888"
  labels:
    opendatahub.io/dashboard: "true"
  name: ovms-1.x
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    openshift.io/display-name: ovms-1.x
  labels:
    opendatahub.io/dashboard: "true"
  containers:
  - name: kserve-container
    image: quay.io/opendatahub/openvino_model_server:stable-nightly-2024-08-04
    args:
      - --model_name={{.Name}}
      - --port=8001
      - --rest_port=8888
      - --model_path=/mnt/models
      - --file_system_poll_wait_seconds=0
      - --grpc_bind_address=0.0.0.0
      - --rest_bind_address=0.0.0.0
      - --target_device=AUTO
      - --metrics_enable
    ports:
      - containerPort: 8888
        protocol: TCP
    volumeMounts:
      - mountPath: /dev/shm
        name: shm
  multiModel: false
  protocolVersions:
    - v2
    - grpc-v2
  supportedModelFormats:
    - autoSelect: true
      name: openvino_ir
      version: opset13
    - name: onnx
      version: "1"
    - autoSelect: true
      name: tensorflow
      version: "1"
    - autoSelect: true
      name: tensorflow
      version: "2"
    - autoSelect: true
      name: paddle
      version: "2"
    - autoSelect: true
      name: pytorch
      version: "2"
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
