apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: "node-role.kubernetes.io/infra="
    scheduler.alpha.kubernetes.io/defaultTolerations: >-
      [{"operator": "Exists", "key":
      "node-role.kubernetes.io/infra"}]
  name: openshift-pipelines
