apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maas-db-config-es
  namespace: redhat-ods-applications
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: openshift-ai-maas-app
        metadataPolicy: None
        property: fqdn-uri
      secretKey: fqdn_uri_var
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: SecretStore
    name: local-k8s-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: maas-db-config
    template:
      data:
        DB_CONNECTION_URL: '{{ .fqdn_uri_var }}'
      engineVersion: v2
      mergePolicy: Replace
      metadata: {}
      type: Opaque
