apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: local-k8s-store
  namespace: redhat-ods-applications
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-secret-reader-sa
      remoteNamespace: maas-db
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
        url: 'https://kubernetes.default.svc'
