apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../overlays/only-nvidia

patches:
  - path: patch-subscription-infra-nodes.yaml
    target:
      kind: Subscription
