apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - console-plugin-job.yaml
  - console-plugin.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: job-kuadrant-console-plugin
    namespace: kuadrant-system
    files:
      - console-plugin-job.sh

replacements:
  - source:
      kind: Subscription
      name: rhcl-operator
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ConsolePlugin
          name: kuadrant-console-plugin
        fieldPaths:
          - spec.backend.service.namespace
