apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - operator-group.yaml
  - subscription.yaml

components:
  - ../components/console-plugin-25
#  Console Plugin Deprecated using helm: see: https://docs.nvidia.com/datacenter/cloud-native/openshift/25.3.2/enable-gpu-monitoring-dashboard.html
