apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-config

resources:
  - oauth.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: htpass-secret
    files:
      - htpasswd=users.htpasswd
