apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

namespace: openshift-nfd

resources:
  - ../../../operator/overlays/stable
  - ../../../instance/overlays/default

patches:
  - target:
      kind: OperatorGroup
      name: nfd
    patch: |-
      - op: replace
        path: "/metadata/name"
        value: openshift-nfd
