apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-gw-options
  namespace: openshift-ingress
data:
  service: |
    spec:
      # ClusterIP avoids provisioning an external LoadBalancer; the OpenShift Route
      # handles external ingress instead.
      type: ClusterIP
  deployment: |
    spec:
      template:
        spec:
          containers:
            - name: istio-proxy
              resources:
                limits:
                    memory: 2Gi
