name: Manifests Validation
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - "*"

jobs:
  lint-kustomize:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Validate Manifests
        run: |
          kustomize version
          touch bootstrap/base/sealed-secrets-secret.yaml
          ./scripts/validate_manifests.sh

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: Validate Manifests
        run: yamllint . -f github

  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Validate Charts
        run: |
          for i in `find "${HELM_DIRS}" -name "Chart.yaml" -exec dirname {} \;`;
          do

            echo
            echo "Validating $i"
            echo

            helm lint $i

            build_response=$?

            if [ $build_response -ne 0 ]; then
              echo "Error linting $i"
              exit 1
            fi

          done

          echo
          echo "Charts successfully validated!"

  validate-git-config:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Validate Repo and Revision
        env:
          EXPECTED_REPO: ${{ github.repositoryUrl }}
        run: |
          REPO_URL=$(echo "${EXPECTED_REPO}" | sed 's/git:\/\//https:\/\//')
          ./scripts/validate_git_config.sh --expected-repo=${REPO_URL} --github

  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.36.0
        with:
          config_path: .spellcheck.yaml
